# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
classes:
  - wso2mb

wso2::service_name: wso2mb
wso2::hostname: mb.dev.wso2.org
wso2::mgt_hostname: mb.dev.wso2.org

wso2::template_list:
  - repository/conf/broker.xml
  - repository/conf/datasources/metrics-datasources.xml
#  - repository/conf/security/cipher-text.properties
#  - repository/conf/security/cipher-tool.properties
#  - bin/ciphertool.sh
#  - password-tmp

#wso2::patch_list:
#  - patch0001

#wso2::file_list:
#  - "repository/components/lib/%{hiera('wso2::datasources::mysql::connector_jar')}"

wso2::mb_thrift_server : "%{::ipaddress}"
wso2::mb_thrift_port: 7611

#wso2::usermgt_datasource: wso2_user_db

wso2::master_datasources:
# Comment the following h2 data source for a clustered setup
  wso2_mb_store_db:
    name: WSO2_MB_STORE_DB
    description: The datasource used for message broker database
    driver_class_name: "%{hiera('wso2::datasources::h2::driver_class_name')}"
    url: jdbc:h2:repository/database/WSO2_MB_STORE_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config: WSO2MBStoreDB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::h2::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

#  wso2_config_db:
#    name: WSO2_CONFIG_DB
#    description: The datasource used for config registry
#    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
#    url: jdbc:mysql://192.168.100.1:3306/WSO2_CONFIG_DB?autoReconnect=true
#    username: "%{hiera('wso2::datasources::mysql::username')}"
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#    jndi_config: jdbc/WSO2_CONFIG_DB
#    max_active: "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
#    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"
#
#  wso2_gov_db:
#    name: WSO2_REG_DB
#    description: The datasource used for gov registry
#    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
#    url: jdbc:mysql://192.168.100.1:3306/WSO2_REG_DB?autoReconnect=true
#    username: "%{hiera('wso2::datasources::mysql::username')}"
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#    jndi_config: jdbc/WSO2_GOV_DB
#    max_active: "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
#    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"
#
#  wso2_user_db:
#    name: WSO2_USER_DB
#    description: The datasource is used for user mangement and userstore
#    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
#    url: jdbc:mysql://192.168.100.1:3306/WSO2_USER_DB?autoReconnect=true
#    username: "%{hiera('wso2::datasources::mysql::username')}"
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#    jndi_config: jdbc/WSO2_USER_DB
#    max_active: "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
#    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"
#
#  wso2_mb_store_db:
#    name: WSO2_MB_STORE_DB
#    description: The datasource used for message database
#    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
#    url: jdbc:mysql://192.168.100.1:3306/WSO2MB_DB?autoReconnect=true
#    username: "%{hiera('wso2::datasources::mysql::username')}"
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#    jndi_config: WSO2MBStoreDB
#    max_active: "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
#    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::metrics_datasources:
# Comment the following h2 data source for a clustered setup
  wso2_metrics_db:
    name: WSO2_METRICS_DB
    description: The default datasource used for WSO2 Carbon Metrics
    driver_class_name: "%{hiera('wso2::datasources::h2::driver_class_name')}"
    url: jdbc:h2:repository/database/WSO2METRICS_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config: jdbc/WSO2MetricsDB
    datasource: WSO2MetricsDB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::h2::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

# Uncomment the following MySQL data source for a clustered setup
#  wso2_metrics_db:
#    name: WSO2_METRICS_DB
#    description: The default datasource used for WSO2 Carbon Metrics
#    driver_class_name: "%{hiera('wso2::datasources::mysql::driver_class_name')}"
#    url: jdbc:mysql://192.168.100.1:3306/WSO2MB_DB?autoReconnect=true
#    username: "%{hiera('wso2::datasources::mysql::username')}"
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#    jndi_config: jdbc/WSO2MetricsDB
#    datasource: WSO2MetricsDB
#    max_active: "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
#    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

# SSO Configuration
wso2::sso_authentication:
  enabled: false
  login_page: /carbon/admin/login.jsp
  service_provider_id: wso2mb
  sso_service_url: https://is.dev.wso2.org:9443/samlsso
  consumer_service_url: https://mb.dev.wso2.org:9443/acs

# Set clustering enabled to true for a clustered setup
wso2::clustering:
  enabled: false
  domain: mb.wso2.domain
  local_member_host: "%{::ipaddress}"
  local_member_port: 4000
# WKA membership scheme
  membership_scheme: wka
  sub_domain: mgt
  wka:
    members:
      -
        hostname: 192.168.100.121
        port: 4000
      -
        hostname: 192.168.100.122
        port: 4000
# AWS membership scheme
#   membership_scheme: aws
#   aws:
#     access_key: access-key
#     secret_key: secret-key
#     security_group: security-group 
#     host_header: host-header
#     region: region
#     tag_key: tag-key
#     tag_value: tag-value

#wso2::registry_mounts:
#  wso2_config_db:
#    path: /_system/config
#    target_path: /_system/config/mb
#    read_only: false
#    registry_root: /
#    enable_cache: true
#
#  wso2_gov_db:
#    path: /_system/governance
#    target_path: /_system/governance
#    read_only: false
#    registry_root: /
#    enable_cache: true

# Secure vault configuration
#wso2::enable_secure_vault: true
#wso2::secure_vault_configs:
#  key_store_password:
#    secret_alias: Carbon.Security.KeyStore.Password
#    secret_alias_value: repository/conf/carbon.xml//Server/Security/KeyStore/Password,false
#    password: "%{hiera('wso2::key_stores::key_store::password')}"
#
#  key_store_key_password:
#    secret_alias: Carbon.Security.KeyStore.KeyPassword
#    secret_alias_value: repository/conf/carbon.xml//Server/Security/KeyStore/KeyPassword,false
#    password: "%{hiera('wso2::key_stores::key_store::key_password')}"
#
#  trust_store_password:
#    secret_alias: Carbon.Security.TrustStore.Password
#    secret_alias_value: repository/conf/carbon.xml//Server/Security/TrustStore/Password,false
#    password: "%{hiera('wso2::key_stores::trust_store::password')}"
#
#  user_manager_admin_password:
#    secret_alias: UserManager.AdminUser.Password
#    secret_alias_value: repository/conf/user-mgt.xml//UserManager/Realm/Configuration/AdminUser/Password,false
#    password: "%{hiera('wso2::super_admin::password')}"
#
#  wso2_carbon_db_password:
#    secret_alias: Datasources.WSO2_CARBON_DB.Configuration.Password
#    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_CARBON_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::common::password')}"
#
#  connector_key_store_password:
#    secret_alias: Server.Service.Connector.keystorePass
#    secret_alias_value: repository/conf/tomcat/catalina-server.xml//Server/Service/Connector[@keystorePass],true
#    password: "%{hiera('wso2::key_stores::connector_key_store::password')}"
#
#  wso2_metrics_db_password:
#    secret_alias: Datasources.WSO2_METRICS_DB.Configuration.Password
#    secret_alias_value: repository/conf/datasources/metrics-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_METRICS_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#
#  transports_amqp_ssl_connection_key_store_password:
#    secret_alias: transports.amqp.sslConnection.keyStore.password
#    secret_alias_value: repository/conf/broker.xml//broker/transports/amqp/sslConnection/keyStore/password,true
#    password: "%{hiera('wso2::key_stores::key_store::password')}"
#
#  transports_amqp_ssl_connection_trust_store_password:
#    secret_alias: transports.amqp.sslConnection.trustStore.password
#    secret_alias_value: repository/conf/broker.xml//broker/transports/amqp/sslConnection/trustStore/password,true
#    password: "%{hiera('wso2::key_stores::trust_store::password')}"
#
#  transports_mqtt_ssl_connection_key_store_password:
#    secret_alias: transports.mqtt.sslConnection.keyStore.password
#    secret_alias_value: repository/conf/broker.xml//broker/transports/mqtt/sslConnection/keyStore/password,true
#    password: "%{hiera('wso2::key_stores::key_store::password')}"
#
#  transports_mqtt_ssl_connection_trust_store_password:
#    secret_alias: transports.mqtt.sslConnection.trustStore.password
#    secret_alias_value: repository/conf/broker.xml//broker/transports/mqtt/sslConnection/trustStore/password,true
#    password: "%{hiera('wso2::key_stores::trust_store::password')}"
#
#  wso2_config_db_password:
#    secret_alias: Datasources.WSO2_CONFIG_DB.Configuration.Password
#    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_CONFIG_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#
#  wso2_gov_db_password:
#    secret_alias: Datasources.WSO2_GOV_DB.Configuration.Password
#    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_GOV_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#
#  wso2_user_db_password:
#    secret_alias: Datasources.WSO2_USER_DB.Configuration.Password
#    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_USER_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: "%{hiera('wso2::datasources::mysql::password')}"
#
#  dep_sync_svn_password:
#    secret_alias: Carbon.DeploymentSynchronizer.SvnPassword
#    secret_alias_value: repository/conf/carbon.xml//Server/DeploymentSynchronizer/SvnPassword,true
#    password: password
